/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.go.sistemainventario.prototipogui;

import br.com.go.sistemainventario.comportamento.ControleSistema;
import br.com.go.sistemainventario.modelo.Endereco;
import br.com.go.sistemainventario.modelo.Fornecedor;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author oliveira
 */
public class JDialogAtualizarFornecedor extends javax.swing.JDialog {

    private Fornecedor fornecedor;

    /**
     * Creates new form JDialogCadastrarFornecedor
     *
     * @param parent
     * @param modal
     */
    private JDialogAtualizarFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.fornecedor = null;
    }

    /**
     * Creates new form JDialogCadastrarFornecedor
     *
     * @param parent
     * @param modal
     * @param fornecedor
     */
    public JDialogAtualizarFornecedor(java.awt.Frame parent, boolean modal, Fornecedor fornecedor) {
        super(parent, modal);
        initComponents();
        this.fornecedor = fornecedor;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfNomeFornecedor = new javax.swing.JTextField();
        jtfContatoFornecedor = new javax.swing.JTextField();
        jtfEmailFornecedor = new javax.swing.JTextField();
        jtfFoneFornecedor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jcbStatusFornecedor = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfLogradouroEndFornecedor = new javax.swing.JTextField();
        jtfNumEndFornecedor = new javax.swing.JTextField();
        jtfCompEndFornecedor = new javax.swing.JTextField();
        jtfBairroEndFornecedor = new javax.swing.JTextField();
        jtfCidadeFornecedor = new javax.swing.JTextField();
        jtfCepEndFornecedor = new javax.swing.JTextField();
        jcbEstadoEndFornecedor = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonAtualizarFornecedor = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel1.setText("Nome Fornecedor:");

        jLabel2.setText("Nome Contato:");

        jLabel3.setText("Email:");

        jLabel4.setText("Telefone");

        jtfNomeFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfContatoFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfEmailFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfFoneFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Status:");

        jcbStatusFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNomeFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfContatoFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfEmailFornecedor)
                            .addComponent(jtfFoneFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbStatusFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfContatoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfFoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcbStatusFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Endereço Fornecedor: "));

        jLabel5.setText("*Logradouro:");

        jLabel6.setText("*Número:");

        jLabel7.setText("Complemento:");

        jLabel8.setText("*Bairro:");

        jLabel9.setText("*Cidade:");

        jLabel10.setText("*CEP:");

        jLabel11.setText("*Estado:");

        jtfLogradouroEndFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfNumEndFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfCompEndFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfBairroEndFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfCidadeFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfCepEndFornecedor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jcbEstadoEndFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel13.setText("Os campos marcados com * são de preenchimento obrigatório.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jtfCepEndFornecedor)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbEstadoEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfCidadeFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfBairroEndFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfCompEndFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfNumEndFornecedor)
                            .addComponent(jtfLogradouroEndFornecedor, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfLogradouroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfNumEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfCompEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfBairroEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfCidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfCepEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbEstadoEndFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonAtualizarFornecedor.setText("Atualizar");
        jButtonAtualizarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarFornecedorActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAtualizarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAtualizarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonAtualizarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarFornecedorActionPerformed
        if (jtfNomeFornecedor.getText().startsWith(" ") || jtfNomeFornecedor.getText().equals("")
                && jtfContatoFornecedor.getText().startsWith(" ") || jtfContatoFornecedor.getText().equals("")
                && jtfEmailFornecedor.getText().startsWith(" ") || jtfEmailFornecedor.getText().equals("")
                && jtfFoneFornecedor.getText().startsWith(" ") || jtfFoneFornecedor.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Favor preencher, nome, "
                    + "contato, email e telefone do Fornecedor");

        } else if (jtfLogradouroEndFornecedor.getText().startsWith(" ") || jtfLogradouroEndFornecedor.getText().equals("")
                && jtfNumEndFornecedor.getText().startsWith(" ") || jtfNumEndFornecedor.getText().equals("")
                && jtfBairroEndFornecedor.getText().startsWith(" ") || jtfBairroEndFornecedor.getText().equals("")
                && jtfCidadeFornecedor.getText().startsWith(" ") || jtfCidadeFornecedor.getText().equals("")
                && jtfCepEndFornecedor.getText().startsWith(" ") || jtfCepEndFornecedor.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Favor preencher os campos obrigatórios"
                    + " do endereço");

        } else {
            Endereco endereco = new Endereco.Builder()
                    .idEndereco(this.fornecedor.getEnderecoFornecedor().getIdEndereco())
                    .logradouroEndereco(jtfLogradouroEndFornecedor.getText())
                    .numEndereco(jtfNumEndFornecedor.getText())
                    .bairroEndereco(jtfBairroEndFornecedor.getText())
                    .cidadeEndereco(jtfCidadeFornecedor.getText())
                    .cepEndereco(jtfCepEndFornecedor.getText())
                    .statusEndereco('A')
                    .construir();

            if (jtfCompEndFornecedor.getText() != null) {
                endereco.setComplementoEndereco(jtfCompEndFornecedor.getText());
            }

            String estado = jcbEstadoEndFornecedor.getSelectedItem().toString();
            endereco.setEstadoEndereco(estado);

            try {
                boolean atualizarEndereco = ControleSistema
                        .enderecoControle()
                        .atualizarEndereco(endereco);

                if (atualizarEndereco) {
                    char statusFornecedor = 'A';

                    switch (jcbStatusFornecedor.getSelectedItem().toString()) {
                        case "Ativo":
                            statusFornecedor = 'A';
                            break;
                        case "Inativo":
                            statusFornecedor = 'I';
                            break;
                    }

                    int idFornecedor = this.fornecedor.getIdFornecedor();
                    this.fornecedor = new Fornecedor.Builder()
                            .idFornecedor(idFornecedor)
                            .enderecoFornecedor(endereco)
                            .nomeFornecedor(jtfNomeFornecedor.getText())
                            .nomeContatoFornecedor(jtfContatoFornecedor.getText())
                            .emailFornecedor(jtfEmailFornecedor.getText())
                            .telefoneFornecedor(jtfFoneFornecedor.getText())
                            .statusFornecedor(statusFornecedor)
                            .construir();

                    boolean atualizarFornecedor = ControleSistema
                            .fornecedorControle()
                            .atualizarFornecedor(fornecedor);

                    if (atualizarFornecedor) {
                        JOptionPane.showMessageDialog(this,
                                "Fornecedor atualizado com sucesso!");
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao atualizar o endereço do Fornecedor."
                            + "\nFavor entrar em contato com o suporte.");
                    this.dispose();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

            this.dispose();
        }
    }//GEN-LAST:event_jButtonAtualizarFornecedorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setTitle("Atualizar Fornecedor");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);

        this.preencherCamposFornecedor();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAtualizarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAtualizarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAtualizarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAtualizarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDialogAtualizarFornecedor dialog = new JDialogAtualizarFornecedor(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarFornecedor;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox jcbEstadoEndFornecedor;
    private javax.swing.JComboBox jcbStatusFornecedor;
    private javax.swing.JTextField jtfBairroEndFornecedor;
    private javax.swing.JTextField jtfCepEndFornecedor;
    private javax.swing.JTextField jtfCidadeFornecedor;
    private javax.swing.JTextField jtfCompEndFornecedor;
    private javax.swing.JTextField jtfContatoFornecedor;
    private javax.swing.JTextField jtfEmailFornecedor;
    private javax.swing.JTextField jtfFoneFornecedor;
    private javax.swing.JTextField jtfLogradouroEndFornecedor;
    private javax.swing.JTextField jtfNomeFornecedor;
    private javax.swing.JTextField jtfNumEndFornecedor;
    // End of variables declaration//GEN-END:variables

    private void preencherCamposFornecedor() {
        this.jtfNomeFornecedor.setText(this.fornecedor.getNomeFornecedor());
        this.jtfContatoFornecedor.setText(this.fornecedor.getNomeContatoFornecedor());
        this.jtfEmailFornecedor.setText(this.fornecedor.getEmailFornecedor());
        this.jtfFoneFornecedor.setText(this.fornecedor.getTelefoneFornecedor());

        char statusFornecedor = this.fornecedor.getStatusFornecedor();

        switch (statusFornecedor) {
            case 'A':
                this.jcbStatusFornecedor.setSelectedIndex(0);
                break;
            case 'I':
                this.jcbStatusFornecedor.setSelectedIndex(1);
                break;
        }

        this.jtfLogradouroEndFornecedor.setText(
                this.fornecedor.getEnderecoFornecedor().getLogradouroEndereco());

        this.jtfNumEndFornecedor.setText(
                this.fornecedor.getEnderecoFornecedor().getNumEndereco());

        if (this.fornecedor.getEnderecoFornecedor().getComplementoEndereco() != null) {
            this.jtfCompEndFornecedor.setText(
                    this.fornecedor.getEnderecoFornecedor().getComplementoEndereco());
        }

        this.jtfBairroEndFornecedor.setText(
                this.fornecedor.getEnderecoFornecedor().getBairroEndereco());

        this.jtfCidadeFornecedor.setText(
                this.fornecedor.getEnderecoFornecedor().getCidadeEndereco());

        this.jtfCepEndFornecedor.setText(
                fornecedor.getEnderecoFornecedor().getCepEndereco());

        this.jcbEstadoEndFornecedor.setSelectedItem(
                this.fornecedor.getEnderecoFornecedor().getEstadoEndereco());
    }
}
