/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.go.sistemainventario.prototipogui;

import br.com.go.sistemainventario.comportamento.ControleSistema;
import br.com.go.sistemainventario.modelo.Equipamento;
import br.com.go.sistemainventario.modelo.Fornecedor;
import br.com.go.sistemainventario.modelo.Localidade;
import br.com.go.sistemainventario.modelo.UsuarioFinal;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author oliveira
 */
public class JDialogCadastrarEquip extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCadastrarEquip
     * @param parent
     * @param modal
     */
    public JDialogCadastrarEquip(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
    }

    private void preencherJComboBoxFornecedor() {
        DefaultComboBoxModel<String> comboBoxFornecedor
                = (DefaultComboBoxModel<String>) jComboBoxFornecedor.getModel();

        ArrayList<Fornecedor> listaFornecedor = null;

        try {
            listaFornecedor = ControleSistema
                    .fornecedorControle()
                    .listarFornecedor();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

        if (listaFornecedor != null) {

            for (Fornecedor fornecedor : listaFornecedor) {
                comboBoxFornecedor.addElement(fornecedor.getIdFornecedor()
                        + "-" + fornecedor.getNomeFornecedor());
            }
        }

        jComboBoxFornecedor.setModel(comboBoxFornecedor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxTipoEquip = new javax.swing.JComboBox();
        jComboBoxOrigemEquip = new javax.swing.JComboBox();
        jtfModeloEquip = new javax.swing.JTextField();
        jtfNumSerie = new javax.swing.JTextField();
        jtfNumSerieGab = new javax.swing.JTextField();
        jtfNumSerieMouse = new javax.swing.JTextField();
        jtfNumSerieTeclado = new javax.swing.JTextField();
        jtfNumSerieMonitor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxFornecedor = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButtonCadastrarEquip = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jLabel1.setText("Tipo do Equipamento: ");

        jLabel2.setText("Origem:");

        jLabel3.setText("Modelo:");

        jLabel4.setText("Nº Série:");

        jLabel5.setText("Nº Série Gabinete:");

        jLabel6.setText("Nº Série Mouse:");

        jLabel7.setText("Nº Série Teclado:");

        jLabel8.setText("Nº Série Monitor:");

        jComboBoxTipoEquip.setMaximumRowCount(4);
        jComboBoxTipoEquip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DESKTOP", "NOTEBOOK", "ALL-IN-ONE", "IMPRESSORA" }));
        jComboBoxTipoEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoEquipActionPerformed(evt);
            }
        });

        jComboBoxOrigemEquip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LOCADO", "PATRIMONIADO" }));
        jComboBoxOrigemEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOrigemEquipActionPerformed(evt);
            }
        });

        jtfModeloEquip.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtfModeloEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfModeloEquipActionPerformed(evt);
            }
        });

        jtfNumSerie.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfNumSerieGab.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfNumSerieMouse.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfNumSerieTeclado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jtfNumSerieMonitor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxOrigemEquip, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTipoEquip, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfModeloEquip)
                    .addComponent(jtfNumSerie)
                    .addComponent(jtfNumSerieGab)
                    .addComponent(jtfNumSerieMouse)
                    .addComponent(jtfNumSerieTeclado)
                    .addComponent(jtfNumSerieMonitor))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxTipoEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxOrigemEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfModeloEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfNumSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfNumSerieGab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfNumSerieMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfNumSerieTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfNumSerieMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fornecedor:"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonCadastrarEquip.setText("Cadastrar");
        jButtonCadastrarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarEquipActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCadastrarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarEquip, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setTitle("Cadastrar Equipamento");
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        
        this.preencherJComboBoxFornecedor();
        //this.jComboBoxFornecedor.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jComboBoxTipoEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoEquipActionPerformed
        int selectedIndex = this.jComboBoxTipoEquip.getSelectedIndex();

        switch (selectedIndex) {
            case 0:
                this.jtfNumSerieGab.setEnabled(true);
                this.jtfNumSerieMouse.setEnabled(true);
                this.jtfNumSerieTeclado.setEnabled(true);
                this.jtfNumSerieMonitor.setEnabled(true);
                break;
            case 1:
                this.jtfNumSerieGab.setEnabled(false);
                this.jtfNumSerieMouse.setEnabled(false);
                this.jtfNumSerieTeclado.setEnabled(false);
                this.jtfNumSerieMonitor.setEnabled(false);
                break;
            case 2:
                this.jtfNumSerieGab.setEnabled(false);
                this.jtfNumSerieMouse.setEnabled(true);
                this.jtfNumSerieTeclado.setEnabled(true);
                this.jtfNumSerieMonitor.setEnabled(false);
                break;
            case 3:
                this.jtfNumSerieGab.setEnabled(false);
                this.jtfNumSerieMouse.setEnabled(false);
                this.jtfNumSerieTeclado.setEnabled(false);
                this.jtfNumSerieMonitor.setEnabled(false);
                break;
        }
    }//GEN-LAST:event_jComboBoxTipoEquipActionPerformed

    private void jtfModeloEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfModeloEquipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfModeloEquipActionPerformed

    private void jComboBoxOrigemEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOrigemEquipActionPerformed
//        int selectedIndex = this.jComboBoxOrigemEquip.getSelectedIndex();
//
//        switch (selectedIndex) {
//            case 0:
//                this.jComboBoxFornecedor.setEnabled(true);
//                break;
//            case 1:
//                this.jComboBoxFornecedor.setSelectedIndex(0);
//                this.jComboBoxFornecedor.setEnabled(false);
//                break;
//        }
    }//GEN-LAST:event_jComboBoxOrigemEquipActionPerformed

    private void jButtonCadastrarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarEquipActionPerformed
        if (isCamposPreenchidos()) {            
            char tipoEquip = this.jComboBoxTipoEquip.getSelectedItem().toString().charAt(0);
            char origemEquip = this.jComboBoxOrigemEquip.getSelectedItem().toString().charAt(0);

            int idFornecedor = getIdFornecedor();

            Equipamento equipamento = new Equipamento.Builder()
                    .tipoEquip(tipoEquip)
                    .origemEquip(origemEquip)
                    .modeloEquip(jtfModeloEquip.getText())
                    .numSerieEquip(jtfNumSerie.getText())
                    .numSerieGabineteEquip(jtfNumSerieGab.getText() + "")
                    .numSerieMouseEquip(jtfNumSerieMouse.getText() + "")
                    .numSerieTecladoEquip(jtfNumSerieTeclado.getText() + "")
                    .numSerieMonitorEquip(jtfNumSerieMonitor.getText() + "")
                    .fornecedor(new Fornecedor.Builder()
                            .idFornecedor(idFornecedor)
                            .construir()
                    )
                    .usarioFinal(new UsuarioFinal.Builder()
                            .idUsuarioFinal(1)
                            .construir()
                    )
                    .localidade(new Localidade.Builder()
                            .idLocalidade(1)
                            .construir()
                    )
                    .construir();
            try {
                
                boolean cadastrarEquipamento = ControleSistema
                        .equipamentoControle()
                        .cadastrarEquipamento(equipamento);
                
                if (cadastrarEquipamento) {
                    JOptionPane.showMessageDialog(this, "Equipamento cadastrado com sucesso!");
                    this.dispose();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(this, "Favor preencher todos os campos necessários.");
        }
    }//GEN-LAST:event_jButtonCadastrarEquipActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastrarEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastrarEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastrarEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastrarEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            JDialogCadastrarEquip dialog = new JDialogCadastrarEquip(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarEquip;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox jComboBoxFornecedor;
    private javax.swing.JComboBox jComboBoxOrigemEquip;
    private javax.swing.JComboBox jComboBoxTipoEquip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jtfModeloEquip;
    private javax.swing.JTextField jtfNumSerie;
    private javax.swing.JTextField jtfNumSerieGab;
    private javax.swing.JTextField jtfNumSerieMonitor;
    private javax.swing.JTextField jtfNumSerieMouse;
    private javax.swing.JTextField jtfNumSerieTeclado;
    // End of variables declaration//GEN-END:variables

    private boolean isCamposPreenchidos() {
        int selectedIndex = this.jComboBoxTipoEquip.getSelectedIndex();

        switch (selectedIndex) {
            case 0:
                return !this.jtfModeloEquip.getText().trim().equals("")
                        && !this.jtfNumSerie.getText().trim().equals("")
                        && !this.jtfNumSerieGab.getText().trim().equals("")
                        && !this.jtfNumSerieMouse.getText().trim().equals("")
                        && !this.jtfNumSerieTeclado.getText().trim().equals("")
                        && !this.jtfNumSerieMonitor.getText().trim().equals("");
            case 1:
                return !this.jtfModeloEquip.getText().trim().equals("")
                        && !this.jtfNumSerie.getText().trim().equals("");
            case 2:
                return !this.jtfModeloEquip.getText().trim().equals("")
                        && !this.jtfNumSerie.getText().trim().equals("")
                        && !this.jtfNumSerieMouse.getText().trim().equals("")
                        && !this.jtfNumSerieTeclado.getText().trim().equals("");
            case 3:
                return !this.jtfModeloEquip.getText().trim().equals("")
                        && !this.jtfNumSerie.getText().trim().equals("");
        }

        return false;
    }

    private int getIdFornecedor() {
        String selectedItem = this.jComboBoxFornecedor.getSelectedItem().toString();

        String[] split = selectedItem.split("-");

        return Integer.parseInt(split[0]);
    }
}
